n_series: 512
length: 512
trend_types: ['linear']
seasonality_types: ['sine']
noise_types: ['none']
trend_params:
  slope: [-1, -0.5]
  intercept: [-30, 30]
  growth_rate: [0, 0]
seasonality_params:
  amplitude: [50, 50]
  period: [128, 128]
noise_params:
  mean: [0, 0]
  stddev: [1, 1]
  low: [0, 0]
  high: [0, 0]
