n_series: 512
length: 512
trend_types: ['none']
seasonality_types: ['sine']
noise_types: ['none']
trend_params:
  slope: [0, 0]
  intercept: [-30, 30]
  growth_rate: [0, 0]
seasonality_params:
  amplitude: [1, 3]
  period: [128, 128]
noise_params:
  mean: [0, 0]
  stddev: [1, 1]
  low: [0, 0]
  high: [0, 0]
